### ISSUE TITLE
Token is expired error

### ISSUE THREAD

**Issue by kyleblarson** [homeaway/homeaway_api_ruby#1]
Hi there.  I am seeing the following error when instantiating a Homeaway client and performing a search:

$ha = HomeAway::API::Client.new(Settings.homeaway.client_id, Settings.homeaway.secret)
$ha.search 'austin, tx'

HomeAway::API::Errors::TokenExpiredError: token is expired, please login again via the oauth url

I previously had this working with a local copy of the gem defined in the homeaway/public-api-developers/tree/master/sdks/ruby_sdk repo, so I was just wondering if I'm using the right gem here.  I also received the notice about the Oauth changes and am curious if this new gem accounts for those changes?

Cheers, 
kyle

**Comment by cemeyer2** [comment]
Hi Kyle,

Please ensure you are on version 1.0.0 of the gem. This version is up to date with the current version of the HomeAway developer API. If you have this version, you should instantiate your client with:

``` ruby
require 'homeaway_api'
client = HomeAway::API::Client.new(client_id: your_client_id, client_secret: your_client_secret)
```

**Comment by kyleblarson** [comment]
Thanks, that helped.  I'm back in action.  I also needed to change my gemfile to require 'homeaway-api' rather than 'homeaway_api'.  That took a minute to figure out. 
Cheers,
Kyle
