### ISSUE TITLE
Search API: Refine params support more than one params defined?

### ISSUE THREAD

**Issue by killercat** [homeaway/homeaway_api_ruby#13]
Hello,

Please help me with this issue :(

From Documentation: refine(string)  -> Refine the search with the given comma delimited refinements (optional comes from a search refinement)   

I need to know if refine parameters from public/search can have more parameters delimited by comma or my understanding is wrong.

First request: https://ws.homeaway.com/public/search?q=austin&pageSize=1&locale=en&refine=Bedrooms:Studio&page=2

return - [size] => 45 and another url request for bedrooms and sleeps like this:
[url] => https://ws.homeaway.com/public/search?q=austin&pageSize=1&locale=en&refine=Sleeps:3,Bedrooms:Studio
[count] => 25

Second request: https://ws.homeaway.com/public/search?q=austin&pageSize=1&locale=en&refine=Sleeps:3,Bedrooms:Studio - 
[size] => 1551 - so the query refine was reseted  - why is not 25? count was 25 for this URL
1. This is how it should behave, only one parameter in refine? Then why the api create the new URL for refine with more that 1 params?
2. it is possible to use search like it is on homeaway.com with "More Filters": Proprety Type, Location Type,Featured etc?

Thanks.
Alina S.

**Comment by cemeyer2** [comment]
Sorry for the delay on this, fell off my radar. You might want to direct this question if it is still outstanding to https://community.homeaway.com/community/developer-api where questions that are not specific to the ruby SDK can be addressed.
