### ISSUE TITLE
Support a user-specified state value

### ISSUE THREAD

**Issue by fetchak** [homeaway/homeaway_api_ruby#15]
Rather than being given a `state` value that the user needs to store in a session or somewhere, it would be ideal if the user could supply their own value.

In our use case, we already have an ideal value to be used for `state` and are already using it in a different OAuth2 integration, so this change would allow code re-use and avoid storing an extra value.

**Comment by fetchak** [comment]
https://github.com/homeaway/homeaway_api_ruby/pull/14

**Comment by cemeyer2** [comment]
merged in #14
