### ISSUE TITLE
Can't revoke tokens

### ISSUE THREAD

**Issue by fetchak** [homeaway/homeaway_api_ruby#16]

**Comment by cemeyer2** [comment]
can you elaborate on this? Thanks!

**Comment by fetchak** [comment]
Basically this https://tools.ietf.org/html/rfc7009

TLDR; API should provide an endpoint that removes access to a given token, aka "log out"

**Comment by cemeyer2** [comment]
Since this appears to be a feature request for the api itself rather than the ruby SDK, can you request this at https://community.homeaway.com/community/developer-api ?
