### ISSUE TITLE
Submit Review API requires a Date not Datetime

### ISSUE THREAD

**Issue by ZenCocoon** [homeaway/homeaway_api_ruby#8]
Currently the `submit_review` endpoint reject datetime and only accept a date of the format `yyyy-MM-dd`.

The spec at `rspec ./spec/submit_review_spec.rb:32` is currently failing with `#<HomeAway::API::Errors::BadRequestError: HomeAway::API::Errors::BadRequestError 400 An arrival date in the form yyyy-MM-dd for the review must be provided.`

Is this something planned to fix on the API side or should the date validator handle the difference between Datetimes and Dates?

**Comment by cemeyer2** [comment]
fixed in 0fccbf71cdde4b7ae0445605c9f8527d3b5649b5
