### ISSUE TITLE
HomeAway::API::Paginator next_page method throws a BadRequestError exception when size > 10

### ISSUE THREAD

**Issue by maximlakin** [homeaway/homeaway_api_ruby#9]
Hi, I noticed that for for paginators with size > 10 the `next_page` method throws an exception:

> HomeAway::API::Errors::BadRequestError: HomeAway::API::Errors::BadRequestError 400

`to_a`, `to_enum` throw the same exception

Thanks for your help!

Max

**Comment by cemeyer2** [comment]
On which api resource are you noticing this behavior? I just attempted to recreate your issue using the results returned from /search, but with a page size of 20, everything worked without error.

**Comment by maximlakin** [comment]
Hey thanks for the quick reply, I'm running:

>  client = HomeAway::API::Client.new(...)
>  reservations = client.my_reservations(propertyId)
> reservations. next_page

**Comment by cemeyer2** [comment]
We have identified the issue and are working on a fix

**Comment by maximlakin** [comment]
Great, thanks!

**Comment by cemeyer2** [comment]
this was fixed in new updates to the HomeAway API service today. Further details are at https://community.homeaway.com/message/202440
